// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace EnergyGameplayTags
{
	/** input **/
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	
	/** Enemy **/
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Attack_Melee);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Attack_Ranged);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Attack_MultiRanged);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Attack_Summon);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Attack_HomingAttack);

	/** Damage **/
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);

	/** HitReact **/
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);

	/** Montage **/
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Montage_Attack_Weapon);
	
	// 추후 사용되는 곳 없으면 삭제
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_Attack_Melee);
	
	

	/** Player **/
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack);

	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Attack_Power);
	
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Attack_Up);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Attack_Down);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Attack_Left);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Attack_Right);

	/** Attribute **/
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Attack_AttackPower);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Attack_DamageMultiplier);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Attack_Range);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Attack_FireRate);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Attack_ShotSpeed);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Attack_ShotCount);

	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Player_MaxHealth);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Player_CurrentHealth);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Player_BaseSpeed);
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Player_SpeedMultiplier);

	/** Event **/
	ENERGYBOLT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_EnergyBolt);
	
}